---
version: "3"
services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: db5432
      POSTGRES_DB: csdb
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always
  web:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - postgres
    volumes:
      - ./pages:/app/pages
      - ./components:/app/components
      - ./styles:/app/styles
      - ./public:/app/public
      - ./lib:/app/lib
      - ./types:/app/types
      - ./database:/app/database
      - ./controllers:/app/controllers
      - ./scripts:/app/scripts
      - ./__tests__:/app/__tests__
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_LISTEN_PORT: 80
      PGADMIN_DEFAULT_PASSWORD: db5432
    ports:
      - 5050:80
    depends_on:
      - postgres
    restart: always
